name: NHL Team Stats Daily

on:
  schedule:
    - cron: "15 10 * * *"     # daily at 10:15 UTC
  workflow_dispatch: {}

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          pwd
          ls -la
          echo "----- .github/workflows -----"
          ls -la .github/workflows || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify DB_URL secret is present (not printing the value)
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python - << 'PY'
          import os, sys
          if not os.environ.get("DB_URL"):
              print("ERROR: DB_URL secret is not set. Add it in Settings → Secrets → Actions.")
              sys.exit(1)
          print("DB_URL secret is set ✅")
          PY

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick DB connectivity test
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python - << 'PY'
          import os, psycopg2
          dsn = os.environ["DB_URL"]
          try:
              conn = psycopg2.connect(dsn)
              cur = conn.cursor()
              cur.execute("SELECT 1;")
              print("DB connection OK ✅")
              cur.close(); conn.close()
          except Exception as e:
              print("DB connection FAILED ❌:", e)
              raise
          PY

      - name: Run loader
        env:
          DB_URL: ${{ secrets.DB_URL }}
          # Optional: override season
          # NHL_SEASON: "20252026"
        run: |
          python daily_nhl_team_stats.py

      - name: Sanity check rows today
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          python - << 'PY'
          import os, psycopg2
          conn = psycopg2.connect(os.environ["DB_URL"])
          cur = conn.cursor()
          cur.execute("SELECT count(*) FROM nhl_team_stats WHERE ingested_at::date = CURRENT_DATE;")
          print("rows_today =", cur.fetchone()[0])
          cur.close(); conn.close()
          PY
