name: NHL Team Stats Daily

on:
  schedule:
    - cron: "15 10 * * *"      # daily at 10:15 UTC
  workflow_dispatch: {}

jobs:
  load:
    runs-on: ubuntu-latest

    env:
      PGHOST: jbzime1eq9.rj87e4urof.tsdb.cloud.timescale.com
      PGPORT: "34545"
      PGDATABASE: tsdb
      PGUSER: tsdbadmin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build DB URL
        env:
          PGPASSWORD: ${{ secrets.TIMESCALE_DB_PASSWORD }}
        run: |
          echo "DB_URL=postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require" >> $GITHUB_ENV

      - name: Quick DB connectivity test
        run: |
          python - << 'PY'
          import os, psycopg2
          conn = psycopg2.connect(os.environ["DB_URL"])
          cur = conn.cursor()
          cur.execute("SELECT 1")
          print("DB connection OK ✅")
          cur.close(); conn.close()
          PY

      - name: Run loader
        run: |
          python daily_nhl_team_stats.py
        env:
          DB_URL: ${{ env.DB_URL }}

      - name: Sanity check rows today
        run: |
          python - << 'PY'
          import os, psycopg2
          conn = psycopg2.connect(os.environ["DB_URL"])
          cur = conn.cursor()
          cur.execute("SELECT count(*) FROM nhl_team_stats WHERE ingested_at::date = CURRENT_DATE;")
          print("rows_today =", cur.fetchone()[0])
          cur.close(); conn.close()
          PY
        env:
          DB_URL: ${{ env.DB_URL }}

